#include "IVolumetricCloudMaterial.h"

#include "VolumetricCloudDefaultMaterial.h"
#include "VolumetricCloudMinimalMaterial.h"

SUBCLASS_DECLARATION_BEGIN(IVolumetricCloudMaterial)
SUBCLASS_DECLARATION(VolumetricCloudDefaultMaterial0)
SUBCLASS_DECLARATION(VolumetricCloudDefaultMaterial1)
SUBCLASS_DECLARATION(VolumetricCloudMinimalMaterial)
SUBCLASS_DECLARATION_END()
